#!/usr/bin/env bash
# configures Nginx to redirect to another page

# first install nginx if not installed
apt-get update -y
apt-get install -y nginx

#update index page
echo "Holberton School for the win!" > /var/www/html/redirect_me
if ! grep -q "redirect_me" /etc/nginx/sites-available/default; then
    sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
fi

# Verfiy the nginx config
nginx -t

# Restart nginx
service nginx restart

sleep 3
