#!/usr/bin/env bash
# Custom 404 page for Nginx

# Configuration variables
NGINX_CONF="/etc/nginx/sites-available/default"
CUSTOM_404_PAGE="/var/www/html/404.html"

#Update the package lists and install Nginx if needed
sudo apt-get update -y
if ! command -v nginx &> /dev/null; then
    sudo apt-get install -y nginx
fi

#Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee $CUSTOM_404_PAGE > /dev/null

# backup the original Nginx config if not backed up yet
if [ ! -f "${NGINX_CONF}.bak" ]; then
    sudo cp "$NGINX_CONF" "${NGINX_CONF}.bak"
fi

#Add the custom 404 page config inside the server block
if ! grep -q "error_page 404" "$NGINX_CONF"; then
    sudo sed -i "/server_name _;/a \\
    error_page 404 /404.html;\\
    location = /404.html {\\
        root /var/www/html;\\
	internal;\\
    }" "$NGINX_CONF"
fi

#test the nginx configuration
sudo nginx -t

#Restart the nginx
sudo service nginx restart
